title: Jan Vitturi
author: Jan Vitturi
url: https://janv.it
permalink: blog/:title
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-titles-from-headings
feed:
  path: blog/feed.xml
titles_from_headings:
  strip_title: true
  collections: true
