title: Jan Vitturi

lang: en
url: https://janv.it
baseurl: ''
permalink: blog/:title

author:
  name: Jan Vitturi
  email: vitturi.jan@gmail.com
  twitter: jan4843

sass:
  style: compressed

compress_html:
  clippings: all
  comments: ["<!--", "-->"]

collections:
  pages:
    output: true

exclude:
  - CNAME
  - '*.taskpaper'
  - '*.sublime-project'

defaults:
  - scope:
      path: '_posts'
    values:
      layout: post
      
  - scope:
      path: '_pages'
    values:
      layout: page
      permalink: :slug
